apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-by-default
  namespace: netflix
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend
  namespace: netflix
spec:
  podSelector:
    matchLabels:
      app: frontend
  ingress:
    - from:
        - namespaceSelector: {} # Allow external load balancer ingress traffic
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-microservices-ingress
  namespace: netflix
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values: [auth-service, user-service, catalog-service, streaming-service, metadata-service, recommendation-service, search-service, billing-service, notification-service]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
        - namespaceSelector: {} # Ingress ALB ingress path controller routing
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-redis-access
  namespace: netflix
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values: [postgres, redis]
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values: [auth-service, user-service, catalog-service, streaming-service, metadata-service, recommendation-service, search-service, billing-service, notification-service]
  policyTypes:
    - Ingress
